@url = http://localhost:3005

GET {{url}}

###

# Obtiene todas las tasks
GET {{url}}/tasks

###

# Obtiene una tarea por id
GET {{url}}/tasks/019c7b07-b36b-7000-89be-64e7588df5a6

###

# Obtiene una tarea por id (ERROR)
GET {{url}}/tasks/019c7b07-b36b-7000-89be-64e7588df5a6222

###

# Crea una nueva tarea
POST {{url}}/tasks
Content-Type: application/json

{
  "title": "Nueva tarea 1"
}

###

# Actualiza una tarea existente
PUT {{url}}/tasks/12345
Content-Type: application/json

{
  "title": "Tarea actualizada"
}

###

# Elimina una tarea por id
DELETE {{url}}/tasks/12345
