@url = http://localhost:3005

GET {{url}}

###

# Obtiene todas las tasks
GET {{url}}/tasks

###

# Obtiene una tarea por id
GET {{url}}/tasks/019c7b07-a44b-7000-82ea-64cca9769691

###

# Obtiene una tarea por id (ERROR)
GET {{url}}/tasks/019c7b07-b36b-7000-89be-64e7588df5a6222

###

# Crea una nueva tarea
POST {{url}}/tasks
Content-Type: application/json

{
  "title": "Nueva tarea 1"
}

###

# Actualiza una tarea existente
PUT {{url}}/tasks/019c9f36-77ea-7000-9c81-6a015fe0a05e
Content-Type: application/json

{
  "title": "Tarea actualizada 4"
}

###

# Elimina una tarea por id
DELETE {{url}}/tasks/019c9f36-77ea-7000-9c81-6a015fe0a05e

###

# Elimina una tarea por id (ERROR
DELETE {{url}}/tasks/019c7b07-bb30-7000-ac0a-2450d224c962278278
