@url = http://localhost:3005

GET {{url}}

###

# Obtiene todas las tasks
GET {{url}}/tasks

###

# Obtiene una tarea por id
GET {{url}}/tasks/019d0b35-e6f5-7000-a558-5cd5fbdd199d

###

# Obtiene una tarea por id (ERROR)
GET {{url}}/tasks/019d0b35-e6f5-7000-a558-5cd5fbdd199d

###

# Crea una nueva tarea
POST {{url}}/tasks
Content-Type: application/json

{
  "title": "Nueva tarea 3"
}

###

# Actualiza una tarea existente
PUT {{url}}/tasks/019d773c-4645-7000-b750-23360c7b1df6
Content-Type: application/json

{
  "title": "Tarea actualizada 2"
}

###

# Elimina una tarea por id
DELETE {{url}}/tasks/019d773c-4645-7000-b750-23360c7b1df6

###

# Elimina una tarea por id (ERROR)
DELETE {{url}}/tasks/019c7b07-bb30-7000-ac0a-2450d224c962278278
